name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-serverless:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_USER: ${{ secrets.GIST_USER }}
          PUBLIC_PATH: /stage/

      - run: yarn deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_USER: ${{ secrets.GIST_USER }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

  deploy-github-ghpages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile
      - run: ( cd app ; yarn build:assets )
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_USER: ${{ secrets.GIST_USER }}
          PUBLIC_PATH: /pizza-tracker/

      - uses: crazy-max/ghaction-github-pages@068e494
        with:
          target_branch: gh-pages
          build_dir: app/.build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GH_PAGES }}
